### ISSUE TITLE
Example data

### ISSUE THREAD

**Issue by Angelablanco7910** [jorgealmerio/QWater#1]
Hi Jorge,

could you please provide some example data in order to test the plugin?

best regards,
Angela

**Comment by jorgealmerio** [comment]
Hi Angela,

You can open a sample Qgis project, to test the plugin, direct from QWater Menu: Plugins\QWater\Projects\

I recommend the Sample Darcy-Weibsbach Liters per second.

best regards,
Jorge Almerio

**Comment by Angelablanco7910** [comment]
Hi Jorge,
Great! Do you have a tutorial of your tool?

It is very impressive!
Best regards
Ángela

**Comment by jorgealmerio** [comment]
Tutorial is still to be done!
Sorry about this! 
But we have a simple tutorial example in Portuguese only.  It was done by a collaborator. You can check it on here on https://github.com/jorgealmerio/QWater at the end of the page.

**Comment by jorgealmerio** [comment]
The tutorial has been translated to english to
[Quick User Guide/Tutorial in English (translated by Neil Falconer)](https://github.com/jorgealmerio/QWater/blob/master/tutorial_en.md)
