### ISSUE TITLE
Import Custom Data

### ISSUE THREAD

**Issue by taetscher** [jorgealmerio/QWater#10]
Hi there!

Thank you for building such an interesting plugin to QGIS!

I was wondering if it is possible to import a custom dataset to work with?

In my case i have an existing cadastre of water pipes. But since it's quite large, I don't really want to recreate every geometry by hand. 
Instead I would like to use the existing data for further processing.

Thanks, Ben

**Comment by jorgealmerio** [comment]
Hi Ben,

As QWater plugin is built over Qgis enviroment, If you can import your network to Qgis you can use the Plugin!
Qgis can Import many formats!

If you want let me know what format you have your dataset maybe I can help you.

Regards,

Jorge Almerio
