### ISSUE TITLE
.inp export from ArcMap

### ISSUE THREAD

**Issue by AGVLE** [jorgealmerio/QWater#11]
Hi folks!

I am Asier, an Agricultural and Environmental engineer recently graduated from UPNA (Public University of Navarre, Spain). I am currently working in a project where I need to export a really large hydraulic network (made from pipes, nodes, hydrants, pumps, tanks, reservoirs, valves, water treatment plants, etc.) from ArcMap 10.8.1 to EPANET. I have already tried to carry out the export with several ESRI-developed tools without any success at the moment. During my undergrad studies i used this tool which i think is very useful, so thank you in advance for your effort and work! Actually i have tried to repeat and use it again for this project but due to several aspects that do not depend on my i am supposed to use ArcMap as the GIS initial software. The tool that i have been used for this project (developed by ESRI) can only export pipes, nodes, hydrants and valves. This tool is based on a .tbx written in python. Is there any idea you have to perform the export correctly from this ESRI software? Do you know any other tool (not GIS-based) with can be used to convert several .shp files into a single .inp file?

**Comment by jorgealmerio** [comment]
Hi, Asier,

There are many tools to achieve your task, for ESRI enviroment I am not updated, but I saw there is a option to use ArcGIS Pro with InfoWater Pro. In the Qgis world there are many other options you can try. Qgis is free so, you can install it and try one of the available plugins about Epanet, including this, QWater.
Let me know more details about the convertion issue if you did not realize it.
