### ISSUE TITLE
On-Demand Irrigation

### ISSUE THREAD

**Issue by jalabanda** [jorgealmerio/QWater#16]
Greetings to everyone.

After many years of using various commercial tools for irrigation network calculations, I believe that the future of these tools lies in working with GIS environments. In my case, I am seeking an application that allows for on-demand irrigation calculations (Clement flow rates). To achieve this, the operational method, at least in the tools I have used so far, would involve specifying the flow rate for each pipe section instead of assigning flow rates per outlet. I am unsure if this is possible with QWater.

Has anyone calculated distribution networks in this manner? How have you resolved it?

Thank you.

**Comment by jorgealmerio** [comment]
Hi, Jalabanda.

QWater uses [Epanet ](https://www.epa.gov/water-research/epanet) engine for calculations. So all the flows rate are calculated based on demand (per outlet). So I don't think it can solve the Clement flow rates the best way). Maybe someone has a better answer.

Thank you for your interest in QWater.

**Comment by jalabanda** [comment]
Hi jorgealmerio, thanks for answering.

**Comment by Artxuloa** [comment]
Hi Jalabanda,

I believe the software you are looking for is SIGOPRAM. It not only computes basic tasks like on demand flow (Clément) flow rates, but it also performs the pipe sizing optimization, and performance analysis integrating EPANET, but it also offers a wide range of tools for land movements, air release valves, hydrant filters, meters, and many more. SIGOPRAM is the GIS software that many of us have been searching for, and there is nothing comparable on the market.

However, please note that it works with ArcMap, NOT OPEN-SOURCE GIS software.
