### ISSUE TITLE
psql: FATAL:  password authentication failed for user "-v"

### ISSUE THREAD

**Issue by tveinot** [jorgealmerio/QWater#2]
I am trying to install QWAT using directions found https://media.readthedocs.org/pdf/qwat/latest/qwat.pdf
but when I get to ./init_qwat.sh -p qwat -s 21781 -d -r the return is psql: FATAL:  password authentication failed for user "-v"
I added host all city-ad/tveinot 127.0.0.1/32 sspi include_realm=0 to my pg_hba.conf file in both the IPv4 and IPV6 lines but still get the authentication error. Does anyone know how to get around this? Using a windows 7.
Thanks
Tyler

**Comment by jorgealmerio** [comment]
You might been talking about "QWAT". It's a different tool. Please add this issue there https://github.com/qwat/QWAT.

**Comment by tveinot** [comment]
Sorry, opened the wrong window...
Thanks;
Tyler
