### ISSUE TITLE
QGIS not responding while running network model in QWATER plugin.

### ISSUE THREAD

**Issue by siddhivinayakchougule** [jorgealmerio/QWater#20]
QGIS not responding while running QWATER model with more than 90k nodes and network length is above 1300 km. Is there any limit for nodes in network model?
I have checked all the system requirements, my pc suitable for that.

**Comment by jorgealmerio** [comment]
I think there is NO model limit. But Qgis may stay in "not responding" status when running big tasks.
Have you tried to wait?

**Comment by siddhivinayakchougule** [comment]
okay thank you. and i waited for almost 24 hours, still the status is not responding.

**Comment by siddhivinayakchougule** [comment]
yes its run after 17 hours. thank you. because of heavy model its taken that much time. is there any way to make this faster?

**Comment by jorgealmerio** [comment]
Good to know! It was an extreme test!

**Comment by siddhivinayakchougule** [comment]
THANK YOU!
