### ISSUE TITLE
Auto naming pipes

### ISSUE THREAD

**Issue by RTwaha** [jorgealmerio/QWater#3]
Hello experts,
I appreciate your effort to create this helpful tool, the plugin has helped me a lot in minimizing time for designing. I used the plugin to design small distribution systems it worked just fine. I'm currently working on a water supply project, the route is very long and i have many nodes to connect my pipes but the plugin does not auto name the nodes to the pipe hence i have to manually name the **NODE1** and **NODE2** to each pipe which is very exhausting. Could there be a fix update to this issue.
**Also** in the new update there is a problem with the **PUMP**, the **DC_ID** in the pump is not recognized with the connected pipe.

**Comment by jorgealmerio** [comment]
Hi,

About the the auto name issue: 
Let me know if you have tried to use the Make Epanet tool, it is the second button from left. If you want to renumber network to make it more meaningful like order it by water direction you can try to use Renumber network tool (3rd button from left) applied to the pipes.

About Pump:
Yesterday I uploaded an update (version 3.0.5) to the plugin that fixes an issue with pumps. Maybe you can check if it solves your problem.

If you want, send me jorgealmerio@yahoo.com.br the shapefile with the network and let me check it.

**Comment by RTwaha** [comment]
Hi George
Thank you for the replay it worked just fine but I stuck on valves. I just sent you a mail please assist.
