### ISSUE TITLE
problem links geometry

### ISSUE THREAD

**Issue by mikip76** [jorgealmerio/QWater#4]
Hi, 
I just started to use it. I notice a problem when I export in inp file,  the geometry of the links are simplify in line, no more polyline.
Where I can download a exemple of valve shapefile. In your version, it is a point and in Ghydraulic it is describe as a line.
Great job. Miki

**Comment by jorgealmerio** [comment]
To use Valves, you have to add point features in the desired locations and fill in the fields: DC_ID, ELEVATION, DIAMETER, TYPE, SETTING, MINORLOSS. Do not forget to set Valve layer in the Settings of the QWater.

Note: You do not need a Valve shapefile sample. Just create a point shapefile, define it on QWater settings as Valve layer and Click on Make epanet model, this will create the Valve layer necessary fields to you.

The availables options to valves Fields are:
•  Diameter: integer Diameter of the valve in mm.
•  Type: string Type of the valve. The following EPANET valve types are valid: 
o	PRV pressure reducing valve
o	PSV pressure sustaining valve
o	PBV pressure breaker valve
o	FCV flow control valve
o	TCV throttle control valve
o	GPV general purpose valve
Additional valve types supported by the QWater plugin: 
o	CV check valve
o	SOV shutoff valve
•  Setting: string Valve type dependent setting. The setting field takes the following values for the different valve types: 
o	PRV the pressure in m
o	PSV the pressure in m
o	PBV the pressure in m
o	FCV the flow in liters per second
o	TCV the loss coefficient
o	GPV the id of the head loss curve
o	CV the setting value will be mapped to the status field of the pipe
o	SOV the setting value will be mapped to the status field of the pipe
•  Minorloss: float Minor loss coefficient of the valve.

**Comment by jorgealmerio** [comment]
About the simplification of polylines to line I will fix it soon,

Thank you!

**Comment by mikip76** [comment]
Great news, waiting for the release.
Thank for your job.

**Comment by jorgealmerio** [comment]
Version 3.1.2 of QWater fixes polylines vertices not exported to INP file
