### ISSUE TITLE
Valve export inp

### ISSUE THREAD

**Issue by mikip76** [jorgealmerio/QWater#5]
Problem with valve exportation in inp :
- diameter property is completed by elevation value
- type property by diameter value
- setting property by type value
- Loss. Coeff property by setting value

[VALVES] ; created by QWater
RP_Bouleyres RP_Bouleyres RP_Bouleyresdn 720.0 400.0 PRV 87.000000 

instead of
RP_Bouleyres RP_Bouleyres RP_Bouleyresdn 400.0 PRV 87.000000

**Comment by jorgealmerio** [comment]
I tested it here now with success and not any elevation field is exported.

Could you help me to find the error?
What is your Qgis and QWater version?
Could you send me the Valve shapefile file?

Thanks,

**Comment by mikip76** [comment]
I tested Qgis 3.4.2-Madeira with Qwater 3.1.2.
I don't have the problem with Ghydraulic 2.1.8. in Qgis 2.18.26. with the same shapefile file

Link for the test
[test.zip](https://github.com/jorgealmerio/QWater/files/2735866/test.zip)
.

**Comment by jorgealmerio** [comment]
Bug fixed on QWater 3.1.3 version, please update it!

Thanks for help!
