### ISSUE TITLE
Make Model

### ISSUE THREAD

**Issue by mikip76** [jorgealmerio/QWater#6]
Thanks for your help (problems solved for valve export + pipe geometry) and great job !
Your extension is great, the best one for Epanet user ! I am using now in Qgis 3.0 (+ 4'000 pipes, 185km)
I am testing Make Model : it should create junction from pipe shapefile, right ?  I have a python error. Let me know.

Link
[test1.zip](https://github.com/jorgealmerio/QWater/files/2741273/test1.zip)

**Comment by jorgealmerio** [comment]
Good to hear you are appreciating the QWater plugin!

After python 3 upgrade many things changed so new issues appeared, sorry about this.

The new QWater version 3.1.4 must solve the junction creation issue.
