### ISSUE TITLE
Possibility to use existing network data 

### ISSUE THREAD

**Issue by iqnaul** [jorgealmerio/QWater#8]
Hi, I have existing pipe and pipe accessories data in shapefiles format. Is it possible for me to use that data to be running on QWater? 

Thank you

**Comment by jorgealmerio** [comment]
Yes, sure. You have to:
1) Set the layer as a pipe layer from QWater settings dialog
2) Use Make model function to create the QWater necessary fields
3) Use Qgis calculator to transfer your existing data to the apropriated QWater fields.
4) Proceed as a the Tutorial [here ](https://github.com/jorgealmerio/QWater/blob/master/README.md) in the main page.

**Comment by iqnaul** [comment]
Ah I see, so the existing data needs to match QWater required fields name and values right?

Thanks Jorge

**Comment by jorgealmerio** [comment]
Fields yes, Values depends of your scenary model.
