### ISSUE TITLE
QWATER-unable to extract elevation from DTM

### ISSUE THREAD

**Issue by DamaniBruno** [jorgealmerio/QWater#9]
I am modeling a small section of pipe line. I overlayed new point files on a DTM. I used Get elevation from raster with Qwater but the elevations are not being extracted from the DTM to the point files. can you assist me?
![Github q1](https://user-images.githubusercontent.com/24724687/66264657-9c6ec200-e7d7-11e9-8220-0e720e1836e5.PNG)

**Comment by jorgealmerio** [comment]
This message is only a warning for points not covered by the raster, they are selected to show you who are they, But the others points should have their elevations (field 'ELEVATION' from attributes table) updated from the raster. If it not been updated, there is somethings that can be happening:
- You did not confirmed the the layer point file as Junctions in QWater settings (Must click the button OK from QWater settings dialog to store settings)
- The raster and the point files are not the same Coordinate system, it would solve this situation, but depends on Qgis version, it can happen.

After that, If you still did not solve, please send me the files (pipes, nodes, raster elevation and qgis project) if you can or tell me more details how to reproduce the problem.
